### ISSUE TITLE
Fix bug tracker link

### ISSUE THREAD

**Issue by adherzog** [jmaslak/Term-Tmux-Layout#6]
The bug tracker link in `tmuxlayout` points at RT, but the link in `Term::Tmux::Layout` points at GitHub.

(I can fix this so they both point at GitHub, but not right now. Just wanted to note it before I forget.)

**Comment by jmaslak** [comment]
Fixed in https://github.com/jmaslak/Term-Tmux-Layout/commit/a911ae693a453e63a6a43e843bd0bf997a2e4957

I will push a new version today.
